#!/bin/bash
# file: re_install_pyvigi.py
# content: de-install, re-install package
# created: 2020 septemeber 27 Sunday
# modified:
# modification:
# author: roch schanen
# comment:
#   make this file executable: ">chmod u+x ./re_install_pyvigi.py"
#   usage : ">./re_install_pyvigi.py"
#   (run script from the pyvigi_dev directory)

pip3 uninstall pyvigi
pip3 install .

# Example:
# -------
# >./re_install_pyvigi 
# Found existing installation: pyvigi 0.0.2
# Uninstalling pyvigi-0.0.2:
#   Would remove:
#     /home/schanen/.local/lib/python3.8/site-packages/pyvigi-0.0.2.dist-info/*
#     /home/schanen/.local/lib/python3.8/site-packages/pyvigi/*
# Proceed (y/n)? y
#   Successfully uninstalled pyvigi-0.0.2
# Processing /home/schanen/work/python3/pyvigi_dev
# Requirement already satisfied: wxpython in /usr/lib/python3/dist-packages (from pyvigi==0.0.2) (4.0.7)
# Requirement already satisfied: numpy in /usr/lib/python3/dist-packages (from wxpython->pyvigi==0.0.2) (1.17.4)
# Building wheels for collected packages: pyvigi
#   Building wheel for pyvigi (setup.py) ... done
#   Created wheel for pyvigi: filename=pyvigi-0.0.2-py3-none-any.whl size=11001 sha256=f4fc97410b759e75e6b46deb8486e3b9d5e43d451a0d1505db2369db9e4017ae
#   Stored in directory: /tmp/pip-ephem-wheel-cache-_0m3vpml/wheels/03/44/cb/f73bfacb19eeb9fb0d602f3686ff18ad1fe35c3f9b91adbf03
# Successfully built pyvigi
# Installing collected packages: pyvigi
# Successfully installed pyvigi-0.0.2
